FROM alpine:latest

ARG SQUID_USER="squid"

ENV SQUID_USER="${SQUID_USER}"

LABEL maintainer="Michael Haken <michael.haken@outlook.com>"

ARG SQUID_PORT="3128"
ARG SQUID_VERSION="4.8-r0"

RUN apk add --no-cache \
        squid="${SQUID_VERSION}" \
    && chown -R squid:squid /var/cache/squid \
    && chown -R squid:squid /var/log/squid \
    && rm -rf /var/cache/apk/*

COPY entrypoint.sh /opt/entrypoint.sh

RUN chmod +x /opt/entrypoint.sh 

EXPOSE "${SQUID_PORT}/tcp"

ENTRYPOINT [ "/opt/entrypoint.sh" ]